# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'react-native-bmk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for react-native-bmk
  pod 'React', :path => '../../node_modules/react-native', :subspecs => [
     'Core'
   ]
   pod "Yoga", :path => "../../node_modules/react-native/ReactCommon/yoga"
   pod "BaiduMapKit_Subspec", :subspecs => [
     'Base',
     'Map',
     'Location',
     'Utils'
   ]
end
